import './styles/globals.css'; // Import the global CSS file with Tailwind
import { ReactNode } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-customGray min-h-screen"> {/* Ensure the page takes full height */}
        <div className="mx-auto"> {/* Container for content */}
          {children}
        </div>
      </body>
    </html>
  );
}
