// app/layout.tsx
import './styles/globals.css'; // Import the global CSS file with Tailwind
import { ReactNode } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-customGray"> {/* You can set a Tailwind class for the background here */}
        {children}
      </body>
    </html>
  );
}